name: Facebook Bot Scheduler

on:
  schedule:
    - cron: "0 * * * *"  # Jalankan setiap jam untuk cek IndexedDB
  workflow_dispatch:  # Bisa dijalankan manual dari GitHub

jobs:
  check-and-run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: 🔹 Checkout repository
        uses: actions/checkout@v3

      - name: 🔹 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 🔹 Install dependencies
        run: npm install

      - name: 🔹 Ambil Jam Terpilih dari IndexedDB (Untuk Autoposting & Marketplace)
        id: get_hours
        run: |
          echo "currentHour=$(node get_hours.js)" >> $GITHUB_ENV

      - name: 🔹 Jalankan Fitur Harian (Autolike, Unfriend, Add Friend, dsb.)
        run: node daily_tasks.js  # Menjalankan fitur harian yang akan berhenti jika batas tercapai

      - name: 🔹 Jalankan Bot Posting Grup (autoposting.js)
        if: env.currentHour == 'true'
        run: node autoposting.js

      - name: 🔹 Jalankan Bot Marketplace (marketplace.js)
        if: env.currentHour == 'true'
        run: node marketplace.js
